feat: homepage added
Malhardixit/quiz-portal pull request #1
Opened 2023-06-16 16:56 UTC by Anish-Parkhi

Added UI for the home page

![image](https://github.com/Malhardixit/quiz-portal/assets/93964690/89433a68-1ac3-4dfb-a073-5eb8be5f09b4)

2023-06-16 16:56 UTC, Malhardixit commented on src/components/Card/Card.jsx
> +                        }
nit:space

2023-06-16 16:57 UTC, Malhardixit commented on src/components/Card/Card.jsx
> +                    }
formatting

2023-06-16 22:02 UTC, Malhardixit commented on src/components/Navbar/Topnav.module.css
> +}
rem

2023-06-16 22:02 UTC, Malhardixit approved these changes
LGTM

2023-06-16 22:04 UTC, Malhardixit requested changes
Please do the changes

2023-06-17 05:28 UTC, Anish-Parkhi commented on src/components/Navbar/Topnav.module.css
> +}
done

2023-06-17 14:02 UTC, Malhardixit approved these changes
LGTM

Squash and merge it to master

2023-06-17 14:02 UTC, Malhardixit commented on src/components/Card/Card.jsx
> +                        {props.title}
name can be better 

className={styles.cardTitle}>

2023-06-17 14:02 UTC, Malhardixit commented on src/components/Card/Card.jsx
> +                        style={{color:"white",fontSize:"70px"}}
7 rem

2023-06-17 17:08 UTC, merged